#.travis.yml

language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - travis_wait 30 npm install -g firebase-tools

script:
  - echo "yolo"

after_success:
  - firebase deploy --token 1/T6l9sPGOsGJpoJLaeL2sDXd3HlZZXhFVD8cGlk1MY5s

notifications:
  email:
    on_failure: change
    on_success: change